### ISSUE TITLE
`Couldn't match expected type ` error when building.

### ISSUE THREAD

**Issue by 573** [liyang/google-search#1]
Hi to compile `google-mail-filters` I want to build this. I kept getting:

> Preprocessing library google-search-0.1.0.1...
> [1 of 2] Compiling Language.Google.Search.Simple ( src\Language\Google\Search\Simple.hs, .stack-work\dist\2672c1f3\build\Language\Google\Search\Simple.o )
> [2 of 2] Compiling Language.Google.Search.Mail ( src\Language\Google\Search\Mail.hs, .stack-work\dist\2672c1f3\build\Language\Google\Search\Mail.o )
> 
> C:\msys64\home\dkahlenberg\google-search-0.1.0.1\src\Language\Google\Search\Mail.hs:165:42:
>     Couldn't match expected type `time-1.5.0.1:Data.Time.Format.Locale.TimeLocale'
>                 with actual type`System.Locale.TimeLocale'
>     NB: `time-1.5.0.1:Data.Time.Format.Locale.TimeLocale'
>           is defined in`Data.Time.Format.Locale' in package `time-1.5.0.1'
> `System.Locale.TimeLocale'
>           is defined in `System.Locale' in package`old-locale-1.0.0.7'
>     In the first argument of `formatTime', namely`defaultTimeLocale'
>     In the second argument of `(.)', namely
> `formatTime defaultTimeLocale "%Y/%m/%d"'
> Completed 23 action(s).
> 
> --  While building package google-search-0.1.0.1 using:
>       C:\Users\dkahlenberg\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build lib:google-search --ghc-options " -ddump-hi -ddump-to-file"
>     Process exited with code: ExitFailure 1

Maybe it has to do with qualified imports or alike.

**Comment by liyang** [comment]
This is due to `time-1.5.0.0` switching to its own `defaultTimeLocale` rather than using `System.Locale.defaultTimeLocale` from `old-locale`. I've fixed this in [`google-mail-filters-0.0.1.2`](https://hackage.haskell.org/package/google-mail-filters-0.0.1.2).
